### ISSUE TITLE
Please verify this login and make sure 2FA is disabled

### ISSUE THREAD

**Issue by zeus1921** [Ashilles/Instagram-DM-Cleaner#2]
Today the script stoped working, and now everytime i try to login this shows up 
![imagem](https://user-images.githubusercontent.com/28808082/177887341-873a5822-a3ff-4776-a6ca-a1cd9669142b.png)

**Comment by ahmedbkd** [comment]
Try to allow this login request first and then restart the tool and login again.

**There is a higher chance of getting this problem if you are running this tool on VPS or RDP, so try to use it on your desktop.**

If it doesn't work, there may be a problem with the user agent so you can try these steps:

- [Change the user agent to your current browser user agent](https://github.com/Ashilles/Instagram-DM-Cleaner/blob/main/run.py#L128)
- Make sure you are not using a proxy or VPN because most of them gets flagged by Instagram as bots.

If the problem persists, please let me know and I will try to fix it.

**Comment by zeus1921** [comment]
nothing :\ weird thing

**Comment by zeus1921** [comment]
also, can u make another option in the menu? (not sure if possible but would be usefull i guess)

3) capture default browser's user agent
 
 then the script would load the user agent so it wont bug anymore! :)

**Comment by zeus1921** [comment]
weird, now it worked hmm.

**Comment by Ashilles** [comment]
I don't have enough details to fix this issue, the problem could be because of outdated headers or outdated user agent.

**Comment by ahmedbkd** [comment]
I don't have enough details to fix this issue, the problem could be because of outdated headers or outdated user agent.
