### ISSUE TITLE
CSRF token

### ISSUE THREAD

**Issue by zeus1921** [Ashilles/Instagram-DM-Cleaner#5]
_Failed getting CSRF token, make sure
  you are connected to the internet._

**Comment by ahmedbkd** [comment]
Instagram has removed the option of logging in with plain passwords from their login endpoint and this is the reason why the tool is giving back this error. The only way to fix this issue is to change the login parameter from `password` to `enc_password`. However, the tool is outdated and does not support this change, making it impossible to get around the enc_password problem. This is because Instagram seems to be using a private algorithm to check the password.
